# Generated by Django 5.2.3 on 2025-07-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_announcement_branddetails_next_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gst_verified', models.BooleanField(default=False)),
                ('is_brand_info_added', models.BooleanField(default=False)),
                ('is_signature_uploaded', models.BooleanField(default=False)),
                ('is_business_preference_set', models.BooleanField(default=False)),
                ('is_warehouse_details_added', models.BooleanField(default=False)),
                ('is_product_details_added', models.BooleanField(default=False)),
                ('is_bank_details_added', models.BooleanField(default=False)),
                ('is_bank_verified', models.BooleanField(default=False)),
                ('is_final_submission_done', models.BooleanField(default=False)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('signature_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('business_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='brand.branduser')),
            ],
        ),
    ]
