# Generated by Django 5.2.3 on 2025-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_brandonboardingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='branduser',
            name='onboarding_status',
            field=models.IntegerField(choices=[(0, 'Phone Not Verified'), (1, 'Email Not Verified'), (2, 'GST Not Verified'), (3, 'Brand Info Not Added'), (4, 'Signature Not Uploaded'), (5, 'Business Preference Not Uploaded'), (6, 'Warehouse Details Not Uploaded'), (7, 'Product Details Not Added'), (8, 'Bank Details Not Uploaded'), (9, 'Final Submission Not Done'), (10, 'Onboarding Complete')], default=0, help_text='Current onboarding step status'),
        ),
        migrations.DeleteModel(
            name='BrandOnboardingStatus',
        ),
    ]
