# Generated by Django 5.2.3 on 2025-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_branduser_business_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branduser',
            name='business_preference',
        ),
        migrations.AddField(
            model_name='branddetails',
            name='business_preference',
            field=models.CharField(blank=True, choices=[('marketplace_only', 'Sell via our Market Place'), ('marketplace_and_api', 'Sell via market place and API also')], help_text='Business preference for selling', max_length=50, null=True),
        ),
    ]
