# Generated by Django 5.2.3 on 2025-07-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_remove_branduser_business_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetails',
            name='daily_order_volume',
            field=models.PositiveIntegerField(blank=True, help_text='Expected daily order volume as integer', null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='signature_id',
            field=models.CharField(blank=True, help_text='ID of the verified signature', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='tan_number',
            field=models.CharField(blank=True, help_text='Tax Account Number', max_length=50, null=True),
        ),
    ]
