# Generated by Django 5.2.3 on 2025-07-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_branddetails_daily_order_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='average_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average order value', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='gender',
            field=models.JSONField(blank=True, help_text='Array of target genders (men, women, kids, unisex)', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='max_age_group',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum target age', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='max_price_range',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price range', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='min_age_group',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum target age', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='min_price_range',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price range', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='product_categories',
            field=models.JSONField(blank=True, help_text='Array of product categories', null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='total_skus',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of SKUs', null=True),
        ),
    ]
