# Generated by Django 5.2.3 on 2025-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_brand_average_order_value_brand_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetails',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='bank_reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='cancelled_cheque_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='is_bank_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='micro_deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branddetails',
            name='verification_status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=0),
        ),
    ]
