# Generated by Django 5.2.3 on 2025-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_branddetails_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetails',
            name='onboarding_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
