# Generated by Django 5.2.3 on 2025-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_branddetails_onboarding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetails',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Number', max_length=15, null=True),
        ),
    ]
