# Generated by Django 5.2.3 on 2025-08-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0012_branddetails_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branddetails',
            name='is_gst_verified',
            field=models.BooleanField(default=False),
        ),
    ]
