# Generated by Django 5.2.3 on 2025-08-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0013_branddetails_is_gst_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['state_name']},
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state_name',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='BrandWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_warehouse', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_warehouses', to='brand.brand')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_warehouses', to='brand.state')),
            ],
            options={
                'unique_together': {('brand', 'state')},
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(related_name='products', through='brand.ProductWarehouse', to='brand.brandwarehouse'),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brandwarehouse'),
        ),
        migrations.RemoveField(
            model_name='state',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
